barrer_button_text:
  default: "Barrer"
  description:
    en: Enter the text for the title of the button in the composer.
barrer_prompt:
  default: "Texte"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.

couleur_button_text:
  default: "Couleur"
  description:
    en: Enter the text for the title of the button in the composer.
couleur_prompt:
  default: "Texte"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.

surligner_button_text:
  default: "Surligner"
  description:
    en: Enter the text for the title of the button in the composer.
surligner_prompt:
  default: "Texte"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.

columns_button:
  default: "Columns"
  description:
    en: Enter the text for the title of the button in the composer.
columns_text:
  default: "Use the closing tag to mark where the first column ends. The second column will autobreak."
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.