en:
  js:
    barrer_button_title: "Highlight Text"
    couleur_button_title: "Underline"
    surligner_button_title: "Center"
    barrer_text: "Text"
    couleur_text: "Text"
    surligner_text: "Text"